# Generated by scripts/homebrew-cask.ts in getalden/alden for v0.3.2. Do not edit by hand.
cask "alden-desktop" do
  version "0.3.2"
  sha256 "5010dd4ad744f6d7b54dc3760eacc06367c2e1009e0252c4a9315a64cd5bb157"

  url "https://github.com/getalden/homebrew-tap/releases/download/v#{version}/Alden-#{version}-universal.dmg"
  name "Alden"
  desc "Code review companion in the menu bar"
  homepage "https://getalden.dev/"

  depends_on macos: ">= :monterey"

  app "Alden.app"

  # The app carries the alden command: link it into Homebrew's bin (already on your PATH), unless the alden formula
  # put one there first.
  postflight do
    command = "#{HOMEBREW_PREFIX}/bin/alden"
    unless File.exist?(command) || File.symlink?(command)
      File.symlink("#{appdir}/Alden.app/Contents/MacOS/alden", command)
    end
  end

  uninstall_postflight do
    command = "#{HOMEBREW_PREFIX}/bin/alden"
    if File.symlink?(command) && File.readlink(command).end_with?("Alden.app/Contents/MacOS/alden")
      File.delete(command)
    end
  end

  # ~/.alden is shared with the alden command line tool, so it stays.
  zap trash: [
    "~/Library/Application Support/dev.getalden.desktop",
    "~/Library/Caches/dev.getalden.desktop",
    "~/Library/Preferences/dev.getalden.desktop.plist",
    "~/Library/Saved Application State/dev.getalden.desktop.savedState",
    "~/Library/WebKit/dev.getalden.desktop",
  ]
end
