# Generated by scripts/homebrew-cask.ts in getalden/alden for v0.2.1. Do not edit by hand.
cask "alden-desktop" do
  version "0.2.1"
  sha256 "fd1e176fc9c6b8cc7ec7d90b8324559ae7a3ed3283b6c842c8f084e665eb09c4"

  url "https://github.com/getalden/homebrew-tap/releases/download/v#{version}/Alden-#{version}-universal.dmg"
  name "Alden"
  desc "Code review companion in the menu bar"
  homepage "https://getalden.dev/"

  depends_on macos: ">= :monterey"

  app "Alden.app"

  # ~/.alden is shared with the alden command line tool, so it stays.
  zap trash: [
    "~/Library/Application Support/dev.getalden.desktop",
    "~/Library/Caches/dev.getalden.desktop",
    "~/Library/Preferences/dev.getalden.desktop.plist",
    "~/Library/Saved Application State/dev.getalden.desktop.savedState",
    "~/Library/WebKit/dev.getalden.desktop",
  ]
end
