# Generated by scripts/homebrew-cask.ts in getalden/alden for v0.2.0. Do not edit by hand.
cask "alden-desktop" do
  version "0.2.0"
  sha256 "cff6a568b3225a6d542b641aaf3be1cca2ce42bb0a1a782f20ff703bcce7c736"

  url "https://github.com/getalden/homebrew-tap/releases/download/v#{version}/Alden-#{version}-universal.dmg"
  name "Alden"
  desc "Code review companion in the menu bar"
  homepage "https://getalden.dev/"

  depends_on macos: ">= :monterey"

  app "Alden.app"

  # ~/.alden is shared with the alden command line tool, so it stays.
  zap trash: [
    "~/Library/Application Support/dev.getalden.desktop",
    "~/Library/Caches/dev.getalden.desktop",
    "~/Library/Preferences/dev.getalden.desktop.plist",
    "~/Library/Saved Application State/dev.getalden.desktop.savedState",
    "~/Library/WebKit/dev.getalden.desktop",
  ]
end
