# Generated by scripts/homebrew-formula.ts in getalden/alden for v0.3.2. Do not edit by hand.
class Alden < Formula
  desc "Code review companion that triages your PR queue and briefs you on each PR"
  homepage "https://getalden.dev"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.2/alden-0.3.2-darwin-arm64.tar.gz"
      sha256 "4db7dc2f2f2a68f6c5a36b0b60281bc59897da3b4fad0f845730d47d4ddcc760"
    end
    on_intel do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.2/alden-0.3.2-darwin-x64.tar.gz"
      sha256 "2c5680ee45396ac9e4e993f6a0451cc8a790c534c4ffbda23b8688124b535389"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.2/alden-0.3.2-linux-arm64.tar.gz"
      sha256 "bc1112e4cd334a601fb48d2d93f37341053590dd820b4d2edabcc07906c51a7b"
    end
    on_intel do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.2/alden-0.3.2-linux-x64.tar.gz"
      sha256 "69d87d68b060fc13bce23191b769f3994b5241db92d42c3832df145fe867bc8a"
    end
  end

  def install
    bin.install "alden"
  end

  test do
    assert_equal "0.3.2", shell_output("ALDEN_NO_UPDATE_CHECK=1 #{bin}/alden --version").strip
  end
end
