# Generated by scripts/homebrew-formula.ts in getalden/alden for v0.3.1. Do not edit by hand.
class Alden < Formula
  desc "Code review companion that triages your PR queue and briefs you on each PR"
  homepage "https://getalden.dev"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.1/alden-0.3.1-darwin-arm64.tar.gz"
      sha256 "8c4014125ccfe889be0d58c916034542822ee1355002fd7386e4e7986dcdbf8f"
    end
    on_intel do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.1/alden-0.3.1-darwin-x64.tar.gz"
      sha256 "83f5f653fb600e9a711b8a0d18fc7b9850902f6826e4c587b2ffeacc946fe8dc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.1/alden-0.3.1-linux-arm64.tar.gz"
      sha256 "6bb414ab7147dc8f9d266fb15f52ae10adeb88727a2e8cfaaf15aa80dbe72c3f"
    end
    on_intel do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.3.1/alden-0.3.1-linux-x64.tar.gz"
      sha256 "a8abda42ccbb26438998baa26d1cbe4da045408e657f6f2b664aeebbaaf9fea0"
    end
  end

  def install
    bin.install "alden"
  end

  test do
    assert_equal "0.3.1", shell_output("ALDEN_NO_UPDATE_CHECK=1 #{bin}/alden --version").strip
  end
end
