# Generated by scripts/homebrew-formula.ts in getalden/alden for v0.2.2. Do not edit by hand.
class Alden < Formula
  desc "Code review companion that triages your PR queue and briefs you on each PR"
  homepage "https://getalden.dev"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.2.2/alden-0.2.2-darwin-arm64.tar.gz"
      sha256 "dad0e0a68332d1fb84b1aca300174604aa58b66010e4a662c87c26fa902309f0"
    end
    on_intel do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.2.2/alden-0.2.2-darwin-x64.tar.gz"
      sha256 "1f3810d75f5450c85920ca587b23faf6ba96ac710b509166d26ea989b900be93"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.2.2/alden-0.2.2-linux-arm64.tar.gz"
      sha256 "742e1612579e3777e617733881ad16cfec4ae059dfbc00f838f9dd30ba2a0e49"
    end
    on_intel do
      url "https://github.com/getalden/homebrew-tap/releases/download/v0.2.2/alden-0.2.2-linux-x64.tar.gz"
      sha256 "8c7deb3b9a3f006a5dad75a723ab72d26da9b938713cfeba21d97aff2c272a92"
    end
  end

  def install
    bin.install "alden"
  end

  test do
    assert_equal "0.2.2", shell_output("ALDEN_NO_UPDATE_CHECK=1 #{bin}/alden --version").strip
  end
end
